### PR TITLE
initial About Us Page

### PR DESCRIPTION
**Pull request by Virgo-Alpha**
Dear @all, kindly have a look at my initial commit. I bet it has a lot of work, including but not limited to:
1. Fonts - I've tried harmonizing but something tells me I need to include a certain library
2. Sizes, spacing - This was tricky but I kind of nailed it to an extent
3. The greater than symbol in the buttons (If it was that at all :)

Having never turned a figma design to a web app, please be kind. Looking forward to reading your recommendations and critiques over the weekend

### CODE REVIEW

**Comment by Emmastro** [comment]
@Virgo-Alpha , this looks nice. Can you rebase from the django branch, and set your files on the home app, in the templates directory? Also, you can check the django documentations to get the statics (CSS, images, etc.) to work from the django setup

**Comment by Virgo-Alpha** [comment]
> 

Done, @Emmastro . Please have a look at my latest commit. Also @all, is it just me or did we forget about the home page?

**Comment by Virgo-Alpha** [comment]
> 

Done, @Emmastro . Please have a look at my latest commit. Also @all, is it just me or did we forget about the home page?

**Comment by Virgo-Alpha** [comment]
I have made an initial view of the home Page as well as updated the README. In both pages (home and aboutUs) I have made a navbar unconventionally. @ianomunga says no need since we are going to standardize them, but I had already done it. You can forgo making the nav bar in your respective pages. You can also ignore the fonts for now because it seems that they are proprietary. I am yet to solve the navigation issue in Django but I'll resolve that by close of business this week.

**Comment by Emmastro** [comment]
thanks @Virgo-Alpha, I'll make some changes directly on your branch before merging with the main branch.

**Pull request merged**
